name:                qb11
version:             0.1.0.0
license:             BSD3
author:              "frostbane"
maintainer:          "frostbane@programmer.net"
copyright:           "2021, 2022 frostbane ac"

extra-source-files:
- README.md
- LICENSE.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/qb11#readme>

dependencies:
- base >= 4.7

library:
  source-dirs: src

executables:
  qb11-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qb11

tests:
  qb11-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qb11
