# GHC 7.8.3    lts-0.0    ~   lts-0.7
# GHC 7.8.4    lts-1.0    ~   lts-2.22
# GHC 7.10.2   lts-3.0    ~   lts-3.22
# GHC 7.10.3   lts-4.0    ~   lts-6.35
# GHC 8.0.1    lts-7.0    ~   lts-7.24
# GHC 8.0.2    lts-8.0    ~   lts-9.21
# GHC 8.2.2    lts-10.0   ~   lts-11.22
# GHC 8.4.3    lts-12.14
# GHC 8.4.4    lts-12.26
# GHC 8.6.3    lts-13.11
# GHC 8.6.4    lts-13.19
# GHC 8.6.5    lts-13.27  ~   lts-14.27
# GHC 8.8.2    lts-15.3
# GHC 8.8.3    lts-16.11
# GHC 8.8.4    lts-16.31
# GHC 8.10.3   lts-17.2
# GHC 8.10.4   lts-18.6
# GHC 8.10.6   lts-18.8
# GHC 8.10.7   lts-18.28
# GHC 9.0.2    lts-19.10  ~   lts-19.33
# GHC 9.2.5    lts-20.5   ~   lts-20.11
# GHC 9.2.6    lts-20.12  ~   lts-20.26
# GHC-9.4.8    lts-21.25  
# GHC-9.6.5    lts-22.22  


# resolver: lts-7.24
## windoze won't compile with 7.24
# 
resolver: lts-12.14
# resolver: lts-22.22

packages:
  - .

extra-deps:
  - mssql-simple-0.6.0.5
  - ms-tds-0.4.0.3

allow-newer: false
