# resolver: lts-3.5
# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
# resolver: https://example.com/snapshots/2018-01-01.yaml
resolver: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/10.yaml

packages:
- .

extra-deps: []

allow-newer: false
